/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Doctor;
import model.DoctorDirectory;
import model.Hospital;
import model.HospitalDirectory;

/**
 *
 * @author karthiksonti
 */
public class CreateDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDoctorsJPanel
     */
    JPanel userProcessContainer;
    DoctorDirectory doctorDirectory;
    HospitalDirectory hospitalDirectory;
    public CreateDoctorJPanel(JPanel userProcessContainer, DoctorDirectory doctorDirectory, HospitalDirectory hospitalDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.doctorDirectory = doctorDirectory;
        this.hospitalDirectory = hospitalDirectory;
        
        doctorHospital.removeAllItems();
        
        //System.out.print(hospitalDirectory);
        for (Hospital h : hospitalDirectory.getHospitalDirectory()) {
            //System.out.print(h.getHospitalName());
            doctorHospital.addItem(h.getHospitalName()+","+ h.getHospitalCommunity()+","+ h.getHospitalCity());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bacckButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        doctorName = new javax.swing.JTextField();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        doctorHospital = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(160, 208, 214));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bacckButton.setText("<<BACK");
        bacckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacckButtonActionPerformed(evt);
            }
        });
        add(bacckButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 36, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Doctor Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 129, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Gender");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 185, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Hospital");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 241, -1, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 282, -1, -1));
        add(doctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 120, 150, 35));

        btnMale.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnMale.setText("Male");
        add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 181, -1, -1));

        btnFemale.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnFemale.setText("Female");
        add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 181, -1, -1));

        doctorHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(doctorHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 237, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bacckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacckButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bacckButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        boolean saveFlag = true;
        Doctor d  = doctorDirectory.addDoctor();
        String doctorNameInput = doctorName.getText();
        
        String doctorHospitalInput = null;
        if(doctorHospital.getItemCount() == 0){
            JOptionPane.showMessageDialog(this, "Please add hospital first");
            saveFlag = false;
            doctorDirectory.removeDoctor(d);
            Doctor.count--;
            return;
        }else{
             doctorHospitalInput = doctorHospital.getSelectedItem().toString();
        }
        
        if(doctorNameInput.isEmpty()){
            JOptionPane.showMessageDialog(this, "Docotr Name can't be empty");
            saveFlag = false;
        }else if(doctorNameInput.matches("[A-Z a-z]*\\s*?") == false){
            JOptionPane.showMessageDialog(this, "Enter valid doctor name");
            saveFlag = false;
        }else if (doctorHospitalInput.isEmpty()){
            JOptionPane.showMessageDialog(this, "Docotor Hospital can't be empty");
            saveFlag = false;
        }else if (btnMale.isSelected() == false && btnFemale.isSelected()== false){
            JOptionPane.showMessageDialog(this, "Please select Docotor Sex ");
            saveFlag = false;
        }
        else if(doctorNameInput.isEmpty() || doctorHospitalInput.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Values can't be null");
            saveFlag = false;
        }
        
                
        if(saveFlag == true){
            if(btnMale.isSelected()){
            String genderMale = btnMale.getText();
            d.setDoctorSex(genderMale);
            }else if(btnFemale.isSelected()){
             String genderFemale = btnFemale.getText();
             d.setDoctorSex(genderFemale);
            }
            d.setDoctorHospital(doctorHospital.getSelectedItem().toString());
            d.setDoctorName(doctorName.getText());
            JOptionPane.showMessageDialog(this, "Data Saved Successfully for Doctor - "+ d.getDoctorName(), "Info", JOptionPane.INFORMATION_MESSAGE);
            clearTextFields();
        }
        else{
            //JOptionPane.showMessageDialog(this, "Information is not saved try again for Hospital");
            doctorDirectory.removeDoctor(d);
            Doctor.count--;
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    
    private void clearTextFields() {
        doctorName.setText("");
        btnMale.setSelected(false);
        btnFemale.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bacckButton;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JComboBox<String> doctorHospital;
    private javax.swing.JTextField doctorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
