/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Hospital;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Hospital;
import model.HospitalDirectory;

/**
 *
 * @author karthiksonti
 */
public class CreateHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateHospitalJPanel
     */
    JPanel userProcessContainer;
    HospitalDirectory hospitalDirectory;
    
    public CreateHospitalJPanel(JPanel userProcessContainer, HospitalDirectory hospitalDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.hospitalDirectory = hospitalDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hospitalName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hospitalCommunity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hospitalCity = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 208, 214));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Hospital Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 149, -1, -1));

        hospitalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalNameActionPerformed(evt);
            }
        });
        add(hospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 141, 150, 35));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Hospital Community");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 207, -1, -1));
        add(hospitalCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 199, 150, 35));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Hospital City");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 260, -1, -1));
        add(hospitalCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 252, 150, 35));

        backButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 40, -1, -1));

        submitButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalNameActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        boolean saveFlag = true;
        
        
        String hospitalNameInput  = hospitalName.getText();
        String hospitalCommunityInput = hospitalCommunity.getText();
        String hospitalCityInput = hospitalCity.getText();
        
        if(hospitalNameInput.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital Name can't be empty");
            saveFlag = false;
        }else if(validateInput(hospitalNameInput) == false ){
           JOptionPane.showMessageDialog(this, "Invalid Hospital Name");
           saveFlag = false;  
        }
        else if (hospitalCommunityInput.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital Community can't be empty");
            saveFlag = false;
        }else if(validateInput(hospitalCommunityInput) == false){
             JOptionPane.showMessageDialog(this, "Invalid Hospital Community");
             saveFlag = false;  
        }else if(hospitalCityInput.isEmpty()){
            JOptionPane.showMessageDialog(this, "Hospital City can't be empty");
            saveFlag = false;
        }else if(validateInput(hospitalCityInput) == false){
             JOptionPane.showMessageDialog(this, "Invalid Hospital City");
             saveFlag = false;  
        }else if(hospitalNameInput.isEmpty() || hospitalCommunityInput.isEmpty() || hospitalCityInput.isEmpty()){
            JOptionPane.showMessageDialog(this, "Values can't be null");
            saveFlag = false;}
        
        if(!hospitalDirectory.getHospitalDirectory().isEmpty()){
            for (Hospital h : hospitalDirectory.getHospitalDirectory()){
                if(h.getHospitalCity().equals(hospitalCity.getText().trim()) && h.getHospitalName().equals(hospitalName.getText().trim()) && h.getHospitalCommunity().equals(hospitalCommunity.getText().trim())){
                    JOptionPane.showMessageDialog(this, "Hospital already exists in : "+h.getHospitalCommunity()+", "+h.getHospitalCity(), "Error", JOptionPane.ERROR_MESSAGE);
                    saveFlag = false;
                }
            }
        }
        
        
        if(saveFlag == true){
            Hospital hospital = hospitalDirectory.addHospital();
            hospital.setHospitalCity(hospitalCity.getText());
            hospital.setHospitalCommunity(hospitalCommunity.getText());
            hospital.setHospitalName(hospitalName.getText());
            JOptionPane.showMessageDialog(this, "Data Saved Successfully for Hospital - "+ hospital.getHospitalName(), "Info",  JOptionPane.INFORMATION_MESSAGE);
            clearTextFields();
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed
    
    private void clearTextFields() {
        hospitalCommunity.setText("");
        hospitalCity.setText("");
        hospitalName.setText("");
    }
    
    private boolean validateInput(String hospitalValues) {
        //String regex = "[a-zA-Z]+";  
        String regex = "[A-Z a-z]*\\s*?";
        return hospitalValues.matches(regex);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField hospitalCity;
    private javax.swing.JTextField hospitalCommunity;
    private javax.swing.JTextField hospitalName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
