/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminArea;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.HospitalDirectory;
import ui.Hospital.CreateHospitalJPanel;
import ui.Hospital.ViewHospitalsJPanel;

/**
 *
 * @author karthiksonti
 */
public class HospitalAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminJPanel
     */
    JPanel userProcessContainer;
    HospitalDirectory hospitalDirectory;
    
    public HospitalAdminJPanel(JPanel userProcessContainer, HospitalDirectory hospitalDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.hospitalDirectory = hospitalDirectory;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createHospitals = new javax.swing.JButton();
        viewHospitals = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 208, 214));

        createHospitals.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        createHospitals.setText("Create Hospitals");
        createHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHospitalsActionPerformed(evt);
            }
        });

        viewHospitals.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        viewHospitals.setText("View Hospitals");
        viewHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHospitalsActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(createHospitals)
                        .addGap(113, 113, 113)
                        .addComponent(viewHospitals))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(backButton)
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createHospitals)
                    .addComponent(viewHospitals)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void createHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHospitalsActionPerformed
        // TODO add your handling code here:
        CreateHospitalJPanel chjp = new CreateHospitalJPanel(userProcessContainer, hospitalDirectory);
        userProcessContainer.add("ManageHospital", chjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createHospitalsActionPerformed

    private void viewHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHospitalsActionPerformed
        // TODO add your handling code here:
        if(hospitalDirectory.getHospitalDirectory().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You cannot view data without entering data!!", "Info",  JOptionPane.INFORMATION_MESSAGE);
        } else {
            ViewHospitalsJPanel vhjp = new ViewHospitalsJPanel(userProcessContainer, hospitalDirectory);
            userProcessContainer.add("ManageHospital", vhjp);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewHospitalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createHospitals;
    private javax.swing.JButton viewHospitals;
    // End of variables declaration//GEN-END:variables
}
